### ISSUE TITLE
install-web.sh not enough RAM

### ISSUE THREAD

**Issue by constancegdl** [Argo-Student-Robotics-Team/WebGUI#2]
When we run the script, either the Rasbpi crashes or we get an error:

npm ERR! code 134
npm ERR! path /home/oracle/WebGUI/openmct
npm ERR! command failed
npm ERR! command sh -c npm run build:prod && npx tsc

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-12-06T15_27_05_555Z-debug-0.log

The full script:
[2023-12-06T15_27_05_555Z-debug-0.log](https://github.com/Argo-Student-Robotics-Team/WebGUI/files/13588182/2023-12-06T15_27_05_555Z-debug-0.log)

@NikolaZgonjanin

**Comment by ElStefanos** [comment]
Cannot run due to insufficient RAM on the RPI. 

npm requires at least 4 GB to run while the RPi4 on the rover has 1 GB.

OpenMCT, and for that matter all web-based telemetry GUI's, require NodeJS and npm to run.
