### ISSUE TITLE
Camera script works but not shown on UI even after URL change

### ISSUE THREAD

**Issue by RKinosaki** [Argo-Student-Robotics-Team/WebGUI#3]
After following the steps of the manual, everything works except for the camera feed, shown in attached picture 1. The messages from running the web script and the camera script is on images 2 and 3 respectively,
![Screenshot from 2024-01-09 14-51-53](https://github.com/Argo-Student-Robotics-Team/WebGUI/assets/105930789/4a8e0ce1-6a65-4ff6-b84b-af755e550be9)
![Screenshot from 2024-01-09 14-53-31](https://github.com/Argo-Student-Robotics-Team/WebGUI/assets/105930789/90a8e987-9e9f-4d82-9790-8489e5a5d678)
![Screenshot from 2024-01-09 14-54-02](https://github.com/Argo-Student-Robotics-Team/WebGUI/assets/105930789/c45316c0-06de-4c98-ae37-85343c7bace2)

**Comment by RKinosaki** [comment]
Ah I did http://:8000, I will try it with the IP

**Comment by ElStefanos** [comment]
> Ah I did http://:8000, I will try it with the IP

Ok, please keep me updated.

**Comment by ElStefanos** [comment]
Since, there was no response, I assume the issue was resolved.
If the issue was not resolved, please open a new issue and refer to this one,
